// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _191_PROJECT_BACKEND.Data;

#nullable disable

namespace _191_PROJECT_BACKEND.Migrations.Order
{
    [DbContext(typeof(OrderContext))]
    [Migration("20230304144027_InitialCreateOrder")]
    partial class InitialCreateOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("_191_PROJECT_BACKEND.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("company_adress")
                        .HasColumnType("TEXT");

                    b.Property<string>("company_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("company_org")
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("internal_note")
                        .HasColumnType("TEXT");

                    b.Property<string>("order")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrderModel");
                });
#pragma warning restore 612, 618
        }
    }
}
